services:
  web:
    image: "ramen-shop:latest"
    ports:
      - "8000:5000"
    healthcheck:
      test: ["CMD-SHELL", "nc", "-z", "127.0.0.1", "5000"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      redis:
        condition: service_healthy
  redis:
    image: "redis:alpine"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
